# Preparation phase

## Import all the necessary libraries

In [1]:
import numpy as np

In [2]:
from pandas import read_csv, DataFrame

In [83]:
import pandas as pd

In [3]:
from sklearn.preprocessing import MinMaxScaler

In [93]:
from typing import Tuple, List, Set

In [63]:
from regex import match

## Write the reusable utility functions

In [94]:
def identify_binary_and_numerical_features(df: DataFrame) -> Tuple[Set[str]]:
     # 1. Identify “binary” columns (unique values ⊆ {0,1})
    categorical_cols = [col for col in df.columns if match(r".+-is_.+", col)]
    
    # 2. All the other numeric columns
    numeric_cols = set(df.columns) - set(categorical_cols)

    # return to a tuple of two lists of column names
    return numeric_cols, categorical_cols

In [95]:
def normalize_numerical_features(df: DataFrame, num_features: Set[str]) -> DataFrame:
    # Create a MinMaxScaler instance
    scaler = MinMaxScaler()

    # Fit and transform the numerical features to the range [0, 1]
    df[list(num_features)] = scaler.fit_transform(df[list(num_features)])
    
    return df

### Make a test of the two utility functions above

In [180]:
appedicities_MAR_15per_missing_dataset = read_csv("amputed_datasets/appendicitis_data/appendicitis_data_amputed_MAR_15_perc.csv")

In [181]:
appedicities_MNAR_15per_missing_dataset = read_csv("amputed_datasets/appendicitis_data/appendicitis_data_amputed_MNAR_15_perc.csv")

In [182]:
feat_m1, feat_c1 = identify_binary_and_numerical_features(appedicities_MAR_15per_missing_dataset)

In [183]:
feat_m2, feat_c2 = identify_binary_and_numerical_features(appedicities_MNAR_15per_missing_dataset)

In [70]:
feat_m1

{'Age',
 'Alvarado_Score',
 'Appendix_Diameter',
 'BMI',
 'Body_Temperature',
 'CRP',
 'Height',
 'Hemoglobin',
 'Length_of_Stay',
 'Neutrophil_Percentage',
 'Paedriatic_Appendicitis_Score',
 'RBC_Count',
 'RDW',
 'Thrombocyte_Count',
 'WBC_Count',
 'Weight'}

In [72]:
feat_m1==feat_m2

True

In [73]:
feat_c1

['Sex-is_female',
 'Sex-is_male',
 'Appendix_on_US-is_yes',
 'Appendix_on_US-is_no',
 'Migratory_Pain-is_no',
 'Migratory_Pain-is_yes',
 'Lower_Right_Abd_Pain-is_yes',
 'Lower_Right_Abd_Pain-is_no',
 'Contralateral_Rebound_Tenderness-is_yes',
 'Contralateral_Rebound_Tenderness-is_no',
 'Coughing_Pain-is_no',
 'Coughing_Pain-is_yes',
 'Nausea-is_no',
 'Nausea-is_yes',
 'Loss_of_Appetite-is_yes',
 'Loss_of_Appetite-is_no',
 'Neutrophilia-is_no',
 'Neutrophilia-is_yes',
 'Ketones_in_Urine-is_++',
 'Ketones_in_Urine-is_no',
 'Ketones_in_Urine-is_+++',
 'Ketones_in_Urine-is_+',
 'RBC_in_Urine-is_+',
 'RBC_in_Urine-is_no',
 'RBC_in_Urine-is_++',
 'RBC_in_Urine-is_+++',
 'WBC_in_Urine-is_no',
 'WBC_in_Urine-is_+',
 'WBC_in_Urine-is_+++',
 'WBC_in_Urine-is_++',
 'Dysuria-is_no',
 'Dysuria-is_yes',
 'Stool-is_normal',
 'Stool-is_constipation',
 'Stool-is_diarrhea',
 'Stool-is_constipation, diarrhea',
 'Peritonitis-is_no',
 'Peritonitis-is_local',
 'Peritonitis-is_generalized',
 'Psoas_Sign-is_yes',
 'Psoas_Sign-is_no',
 'Ipsilateral_Rebound_Tenderness-is_no',
 'Ipsilateral_Rebound_Tenderness-is_yes',
 'US_Performed-is_yes',
 'US_Performed-is_no',
 'Free_Fluids-is_no',
 'Free_Fluids-is_yes',
 'Appendix_Wall_Layers-is_intact',
 'Appendix_Wall_Layers-is_raised',
 'Appendix_Wall_Layers-is_upset',
 'Appendix_Wall_Layers-is_partially raised',
 'Surrounding_Tissue_Reaction-is_yes',
 'Surrounding_Tissue_Reaction-is_no',
 'Pathological_Lymph_Nodes-is_yes',
 'Pathological_Lymph_Nodes-is_no']

In [74]:
feat_c1 == feat_c2

True

In [80]:
%%bash
ls preprocessed_datasets/*

preprocessed_datasets/HCV_Egyptian_data_complete.csv
preprocessed_datasets/HCV_data_imputed.csv
preprocessed_datasets/HCV_data_unimputed.csv
preprocessed_datasets/Heart_Failure_Clinical_Records_complete.csv
preprocessed_datasets/Indian_liver_patients_imputed.csv
preprocessed_datasets/Indian_liver_patients_unimputed.csv
preprocessed_datasets/Regensburg_Pediatric_Appendicitis_imputed.csv
preprocessed_datasets/Regensburg_Pediatric_Appendicitis_unimputed.csv

In [96]:
normalized_appendicities_df = normalize_numerical_features(appedicities_MAR_15per_missing_dataset, feat_m1)

In [98]:
normalized_appendicities_df[list(feat_m1)].describe()

,RBC_Count,CRP,Appendix_Diameter,Height,BMI,WBC_Count,Paedriatic_Appendicitis_Score,Age,Body_Temperature,Neutrophil_Percentage,Thrombocyte_Count,Alvarado_Score,Length_of_Stay,RDW,Weight,Hemoglobin
count,593.000000,625.000000,592.000000,611.000000,598.000000,603.000000,606.000000,580.000000,617.000000,605.000000,600.000000,608.000000,604.000000,616.000000,607.000000,608.000000
mean,0.098671,0.091612,0.329630,0.681818,0.359275,0.307825,0.515182,0.618119,0.786537,0.642567,0.428927,0.573329,0.145281,0.025183,0.390884,0.557452
std,0.051260,0.138088,0.150391,0.139218,0.143265,0.158022,0.196742,0.188898,0.068582,0.210374,0.149683,0.212106,0.100241,0.054218,0.173400,0.117759
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.072478,0.022700,0.219858,0.604317,0.256347,0.179153,0.400000,0.503268,0.744361,0.468657,0.323725,0.400000,0.100000,0.014531,0.252827,0.483871
50%,0.095984,0.036124,0.310781,0.690647,0.329377,0.283388,0.500000,0.620643,0.774436,0.676119,0.414634,0.600000,0.100000,0.019815,0.371971,0.556721
75%,0.119491,0.092507,0.432624,0.787050,0.434224,0.420195,0.600000,0.761574,0.827068,0.816418,0.523836,0.774772,0.150000,0.027741,0.505250,0.623656
max,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

the test is successful

<hr/>

Let's remind ourselves that, in the next part of this study (VAEQL implementation, we will discretize the <code>[0, 1]</code> normalized the numerical features into 101 states to faciliate the Q-learning) using the <code>round</code> method

<hr/>

### Create the utility functions that compares the processed unimputed/imputed datasets and the amputed dataset to create the missingness masks

In [189]:
def generate_masks_for_missingness(
    original_df: pd.DataFrame,  
    amputed_df: pd.DataFrame,
    num_feats: Set[str],
    cat_feats: Set[str],
    imputed_original_df: pd.DataFrame = None,
) -> Tuple[np.ndarray, np.ndarray]:

    if not type(imputed_original_df) == pd.DataFrame:
        print("No missingness!")
        imputed_original_df = original_df.copy()

    # Check if the dataframes match in shape
    if not original_df.shape == imputed_original_df.shape == amputed_df.shape:
        raise Exception("Sorry, the three dataframes do not match in shape")

    # Check if the dataframes have identical column names
    if not set(original_df.columns) == set(imputed_original_df.columns) == set(amputed_df.columns):
        raise Exception("Sorry, the three dataframes do not match in column names")

    num_feats = list(num_feats)
    cat_feats = list(cat_feats)

    # Initialize the maps for numerical and categorical features
    num_feat_map = np.zeros(original_df[num_feats].shape, dtype=int)
    cat_feat_map = np.zeros(original_df[cat_feats].shape, dtype=int)
    
    # Generate the missingness map for numerical features
    for i, feat in enumerate(num_feats):
        original_col = original_df[feat]
        amputed_col = amputed_df[feat]
        
        # 1: missing in the original dataset, regardless of whether it is amputed
        num_feat_map[:, i] = np.where(original_col.isna(), 1, 0)  # 1 if missing originally, otherwise 0
        # 2: existing in the original dataset and amputed
        num_feat_map[:, i] = np.where(amputed_col.isna(), 2, num_feat_map[:, i])  # 2 if amputed
    
    # Generate the missingness map for one-hot-encoded categorical features
    for i, feat in enumerate(cat_feats):
        original_col = original_df[feat]
        amputed_col = amputed_df[feat]
        
        # 1: missing in the original dataset, regardless of whether it is amputed
        cat_feat_map[:, i] = np.where(original_col.isna(), 1, 0)  # 1 if missing originally, otherwise 0
        # 2: existing in the original dataset and amputed
        cat_feat_map[:, i] = np.where(amputed_col.isna(), 2, cat_feat_map[:, i])  # 2 if amputed

    # Return the maps as a tuple of two arrays
    return num_feat_map, cat_feat_map

### Make a test of the two utility functions above

#### Testing <code>generate_masks_for_missingnes</code> using the <code>Regensburg Appenticitis Dataset</code> (with pre-existing missingness)

##### Read the datasets

In [108]:
%%bash
ls *datasets

amputed_datasets:
HCV_Egyptian_patients
HCV_data
Indian_liver_patients
appendicitis_data
heart_failure_clinical_records

preprocessed_datasets:
HCV_Egyptian_data_complete.csv
HCV_data_imputed.csv
HCV_data_unimputed.csv
Heart_Failure_Clinical_Records_complete.csv
Indian_liver_patients_imputed.csv
Indian_liver_patients_unimputed.csv
Regensburg_Pediatric_Appendicitis_imputed.csv
Regensburg_Pediatric_Appendicitis_unimputed.csv

In [109]:
%%bash
ls amputed_datasets/appendicitis_data

appendicitis_data_amputed_MAR_10_perc.csv
appendicitis_data_amputed_MAR_15_perc.csv
appendicitis_data_amputed_MAR_20_perc.csv
appendicitis_data_amputed_MAR_25_perc.csv
appendicitis_data_amputed_MAR_5_perc.csv
appendicitis_data_amputed_MNAR_10_perc.csv
appendicitis_data_amputed_MNAR_15_perc.csv
appendicitis_data_amputed_MNAR_20_perc.csv
appendicitis_data_amputed_MNAR_25_perc.csv
appendicitis_data_amputed_MNAR_5_perc.csv

In [176]:
test_apd_df_MAR = pd.read_csv("amputed_datasets/appendicitis_data/appendicitis_data_amputed_MAR_15_perc.csv")
test_apd_df_MNAR = pd.read_csv("amputed_datasets/appendicitis_data/appendicitis_data_amputed_MNAR_20_perc.csv")
ref_apd_df = pd.read_csv("preprocessed_datasets/Regensburg_Pediatric_Appendicitis_unimputed.csv")
imputed_apd_df = pd.read_csv("preprocessed_datasets/Regensburg_Pediatric_Appendicitis_unimputed.csv")

In [242]:
feat_m1, feat_c1 = identify_binary_and_numerical_features(appedicities_MAR_15per_missing_dataset)

In [229]:
test_apd_MAR_mask_num, test_apd_MAR_mask_cat = generate_masks_for_missingness(
    ref_apd_df,  
    test_apd_df_MAR,
    feat_m1,
    feat_c1,
    imputed_original_df = imputed_apd_df
)

In [228]:
test_apd_MNAR_mask_num, test_apd_MNAR_mask_cat = generate_masks_for_missingness(
    ref_apd_df,
    test_apd_df_MNAR,
    feat_m1, 
    feat_c1,
    imputed_original_df = imputed_apd_df
)

##### Testing the correctness of these maps

In [192]:
test_apd_MAR_mask_num

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 1, ..., 0, 0, 2],
       [0, 0, 1, ..., 0, 0, 0],
       ...,
       [0, 0, 1, ..., 0, 0, 0],
       [0, 0, 0, ..., 2, 2, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [243]:
test_apd_df_MAR[list(feat_m1)]

,RBC_Count,CRP,Appendix_Diameter,Height,BMI,WBC_Count,Paedriatic_Appendicitis_Score,Age,Body_Temperature,Neutrophil_Percentage,Thrombocyte_Count,Alvarado_Score,Length_of_Stay,RDW,Weight,Hemoglobin
0,5.27,0.0,7.100000,148.0,16.90,NaN,3.0,12.68,37.0,68.2,254.0,4.0,3.0,12.2,37.0,14.8
1,5.26,3.0,7.596999,147.0,31.90,8.1,NaN,NaN,36.9,64.8,151.0,5.0,NaN,12.7,69.5,NaN
2,3.98,3.0,7.864903,NaN,23.30,13.2,3.0,14.14,36.6,74.8,300.0,NaN,4.0,12.2,62.0,11.4
3,4.64,0.0,7.195974,165.0,20.60,11.4,6.0,16.37,36.0,63.0,258.0,7.0,3.0,13.2,56.0,13.6
4,4.44,0.0,NaN,163.0,16.90,8.1,6.0,11.08,36.9,44.0,311.0,5.0,3.0,13.6,NaN,12.6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
708,4.49,0.0,6.926934,151.0,19.74,8.8,6.0,14.35,38.0,58.5,246.0,4.0,7.0,12.2,45.0,13.8
709,4.95,71.0,7.500000,NaN,25.25,NaN,NaN,12.41,39.4,76.6,NaN,NaN,NaN,13.4,NaN,13.7
710,4.49,2.0,7.387729,152.0,19.91,14.6,3.0,14.99,37.3,68.5,328.0,5.0,4.0,12.8,46.0,12.7
711,4.97,8.0,14.000000,NaN,14.30,17.8,8.0,7.20,NaN,77.0,345.0,9.0,5.0,NaN,NaN,14.3
712,4.64,1.0,8.000000,146.5,18.17,9.3,2.0,11.51,36.8,70.0,291.0,2.0,4.0,12.7,39.0,13.2

In [230]:
test_apd_MAR_mask_cat

array([[0, 0, 0, ..., 0, 0, 0],
       [2, 2, 0, ..., 1, 1, 1],
       [0, 0, 2, ..., 1, 1, 1],
       ...,
       [0, 0, 2, ..., 1, 1, 1],
       [2, 2, 0, ..., 0, 2, 2],
       [0, 0, 2, ..., 0, 2, 2]])

In [196]:
test_apd_df_MAR[list(feat_c1)]

,Sex-is_female,Sex-is_male,Appendix_on_US-is_yes,Appendix_on_US-is_no,Migratory_Pain-is_no,Migratory_Pain-is_yes,Lower_Right_Abd_Pain-is_yes,Lower_Right_Abd_Pain-is_no,Contralateral_Rebound_Tenderness-is_yes,Contralateral_Rebound_Tenderness-is_no,...,Free_Fluids-is_no,Free_Fluids-is_yes,Appendix_Wall_Layers-is_intact,Appendix_Wall_Layers-is_raised,Appendix_Wall_Layers-is_upset,Appendix_Wall_Layers-is_partially raised,Surrounding_Tissue_Reaction-is_yes,Surrounding_Tissue_Reaction-is_no,Pathological_Lymph_Nodes-is_yes,Pathological_Lymph_Nodes-is_no
0,1.0,0.0,1.0,0.0,NaN,NaN,NaN,NaN,1.0,0.0,...,1.0,0.0,1.000000,0.000000,0.000000,0.000000,1.000000,0.000000,1.000000,0.000000
1,NaN,NaN,0.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0,...,1.0,0.0,0.615023,0.342723,0.004695,0.037559,0.821577,0.178423,0.765306,0.234694
2,1.0,0.0,NaN,NaN,1.0,0.0,1.0,0.0,1.0,0.0,...,1.0,0.0,0.615023,0.342723,0.004695,0.037559,0.821577,0.178423,0.765306,0.234694
3,1.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,1.0,...,1.0,0.0,NaN,NaN,NaN,NaN,0.821577,0.178423,1.000000,0.000000
4,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,0.821577,0.178423,1.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
708,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,NaN,NaN,...,1.0,0.0,0.615023,0.342723,0.004695,0.037559,0.821577,0.178423,0.765306,0.234694
709,NaN,NaN,1.0,0.0,0.0,1.0,1.0,0.0,NaN,NaN,...,1.0,0.0,NaN,NaN,NaN,NaN,0.821577,0.178423,0.765306,0.234694
710,1.0,0.0,NaN,NaN,1.0,0.0,1.0,0.0,0.0,1.0,...,NaN,NaN,0.615023,0.342723,0.004695,0.037559,0.821577,0.178423,0.765306,0.234694
711,NaN,NaN,1.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,...,0.0,1.0,0.615024,0.342723,0.004695,0.037558,1.000000,0.000000,NaN,NaN
712,0.0,1.0,NaN,NaN,1.0,0.0,1.0,0.0,NaN,NaN,...,1.0,0.0,0.000000,1.000000,0.000000,0.000000,1.000000,0.000000,NaN,NaN

In [197]:
test_apd_MNAR_mask_num

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 1, ..., 0, 0, 2],
       [0, 0, 1, ..., 0, 2, 0],
       ...,
       [0, 0, 1, ..., 0, 0, 0],
       [0, 0, 2, ..., 0, 2, 0],
       [0, 0, 0, ..., 0, 2, 0]])

In [198]:
ref_apd_df[list(feat_m1)]

,RBC_Count,CRP,Appendix_Diameter,Height,BMI,WBC_Count,Paedriatic_Appendicitis_Score,Age,Body_Temperature,Neutrophil_Percentage,Thrombocyte_Count,Alvarado_Score,Length_of_Stay,RDW,Weight,Hemoglobin
0,5.27,0.0,7.1,148.0,16.90,7.7,3.0,12.68,37.0,68.2,254.0,4.0,3.0,12.2,37.0,14.8
1,5.26,3.0,NaN,147.0,31.90,8.1,4.0,14.10,36.9,64.8,151.0,5.0,2.0,12.7,69.5,15.7
2,3.98,3.0,NaN,163.0,23.30,13.2,3.0,14.14,36.6,74.8,300.0,5.0,4.0,12.2,62.0,11.4
3,4.64,0.0,NaN,165.0,20.60,11.4,6.0,16.37,36.0,63.0,258.0,7.0,3.0,13.2,56.0,13.6
4,4.44,0.0,7.0,163.0,16.90,8.1,6.0,11.08,36.9,44.0,311.0,5.0,3.0,13.6,45.0,12.6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
708,4.49,0.0,NaN,151.0,19.74,8.8,6.0,14.35,38.0,58.5,246.0,4.0,7.0,12.2,45.0,13.8
709,4.95,71.0,7.5,166.5,25.25,11.4,7.0,12.41,39.4,76.6,243.0,8.0,4.0,13.4,70.0,13.7
710,4.49,2.0,NaN,152.0,19.91,14.6,3.0,14.99,37.3,68.5,328.0,5.0,4.0,12.8,46.0,12.7
711,4.97,8.0,14.0,129.3,14.30,17.8,8.0,7.20,37.5,77.0,345.0,9.0,5.0,12.7,23.9,14.3
712,4.64,1.0,8.0,146.5,18.17,9.3,2.0,11.51,36.8,70.0,291.0,2.0,4.0,12.7,39.0,13.2

In [199]:
test_apd_df_MNAR[list(feat_m1)]

,RBC_Count,CRP,Appendix_Diameter,Height,BMI,WBC_Count,Paedriatic_Appendicitis_Score,Age,Body_Temperature,Neutrophil_Percentage,Thrombocyte_Count,Alvarado_Score,Length_of_Stay,RDW,Weight,Hemoglobin
0,5.27,0.0,7.100000,148.0,16.90,7.7,3.0,12.68,37.0,68.2,254.0,4.0,3.0,12.2,37.0,14.8
1,5.26,3.0,7.596999,147.0,31.90,8.1,4.0,14.10,36.9,64.8,151.0,5.0,2.0,12.7,69.5,NaN
2,3.98,3.0,7.864903,163.0,23.30,13.2,NaN,14.14,36.6,74.8,300.0,5.0,4.0,12.2,NaN,11.4
3,4.64,0.0,7.195974,165.0,NaN,11.4,NaN,NaN,36.0,63.0,NaN,7.0,3.0,13.2,56.0,13.6
4,4.44,0.0,7.000000,163.0,16.90,8.1,6.0,11.08,36.9,44.0,311.0,5.0,3.0,13.6,NaN,12.6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
708,NaN,0.0,6.926934,151.0,NaN,8.8,NaN,14.35,NaN,58.5,246.0,4.0,7.0,12.2,45.0,NaN
709,4.95,NaN,7.500000,166.5,25.25,11.4,NaN,12.41,NaN,NaN,243.0,8.0,4.0,13.4,NaN,NaN
710,4.49,2.0,7.387729,152.0,19.91,14.6,3.0,NaN,NaN,68.5,328.0,5.0,4.0,12.8,46.0,12.7
711,4.97,8.0,NaN,129.3,14.30,NaN,NaN,7.20,37.5,NaN,345.0,9.0,5.0,12.7,NaN,14.3
712,4.64,1.0,8.000000,146.5,18.17,9.3,2.0,11.51,NaN,NaN,NaN,2.0,4.0,12.7,NaN,13.2

In [232]:
test_apd_MNAR_mask_cat

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 2, ..., 1, 1, 1],
       [0, 0, 0, ..., 2, 1, 1],
       ...,
       [0, 0, 0, ..., 1, 1, 1],
       [2, 2, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 2, 2]])

In [201]:
test_apd_df_MNAR[list(feat_c1)]

,Sex-is_female,Sex-is_male,Appendix_on_US-is_yes,Appendix_on_US-is_no,Migratory_Pain-is_no,Migratory_Pain-is_yes,Lower_Right_Abd_Pain-is_yes,Lower_Right_Abd_Pain-is_no,Contralateral_Rebound_Tenderness-is_yes,Contralateral_Rebound_Tenderness-is_no,...,Free_Fluids-is_no,Free_Fluids-is_yes,Appendix_Wall_Layers-is_intact,Appendix_Wall_Layers-is_raised,Appendix_Wall_Layers-is_upset,Appendix_Wall_Layers-is_partially raised,Surrounding_Tissue_Reaction-is_yes,Surrounding_Tissue_Reaction-is_no,Pathological_Lymph_Nodes-is_yes,Pathological_Lymph_Nodes-is_no
0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,...,1.0,0.0,1.000000,0.000000,0.000000,0.000000,1.000000,0.000000,1.000000,0.000000
1,0.0,1.0,NaN,NaN,0.0,1.0,1.0,0.0,NaN,NaN,...,1.0,0.0,0.615023,0.342723,0.004695,0.037559,0.821577,0.178423,0.765306,0.234694
2,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,...,1.0,0.0,0.615023,0.342723,0.004695,0.037559,NaN,NaN,0.765306,0.234694
3,1.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,1.0,...,1.0,0.0,0.615023,0.342723,0.004695,0.037559,0.821577,0.178423,1.000000,0.000000
4,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,...,1.0,0.0,0.615024,0.342723,0.004695,0.037558,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
708,NaN,NaN,0.0,1.0,1.0,0.0,1.0,0.0,0.0,1.0,...,1.0,0.0,0.615023,0.342723,0.004695,0.037559,0.821577,0.178423,0.765306,0.234694
709,NaN,NaN,1.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,...,1.0,0.0,0.000000,1.000000,0.000000,0.000000,0.821577,0.178423,0.765306,0.234694
710,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,1.0,...,0.0,1.0,0.615023,0.342723,0.004695,0.037559,0.821577,0.178423,0.765306,0.234694
711,NaN,NaN,1.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,...,0.0,1.0,NaN,NaN,NaN,NaN,1.000000,0.000000,0.000000,1.000000
712,0.0,1.0,1.0,0.0,1.0,0.0,NaN,NaN,0.0,1.0,...,1.0,0.0,0.000000,1.000000,0.000000,0.000000,1.000000,0.000000,NaN,NaN

all of them are correct!

#### Testing <code>generate_masks_for_missingnes</code> using the <code>Heart Failure Clinical Records</code> (without pre-existing missingness)

##### Read the datasets

In [202]:
%%bash
ls amputed_datasets/heart_failure_clinical_records

heart_failure_amputed_MAR_10_perc.csv
heart_failure_amputed_MAR_15_perc.csv
heart_failure_amputed_MAR_20_perc.csv
heart_failure_amputed_MAR_25_perc.csv
heart_failure_amputed_MAR_5_perc.csv
heart_failure_data_amputed_MNAR_10_perc.csv
heart_failure_data_amputed_MNAR_15_perc.csv
heart_failure_data_amputed_MNAR_20_perc.csv
heart_failure_data_amputed_MNAR_25_perc.csv
heart_failure_data_amputed_MNAR_5_perc.csv

In [207]:
test_hf_df_MAR = pd.read_csv("amputed_datasets/heart_failure_clinical_records/heart_failure_amputed_MAR_20_perc.csv")
test_hf_df_MNAR = pd.read_csv("amputed_datasets/heart_failure_clinical_records/heart_failure_data_amputed_MNAR_15_perc.csv")
ref_hf_df = pd.read_csv("preprocessed_datasets/Heart_Failure_Clinical_Records_complete.csv")

In [239]:
feat_m2, feat_c2 = identify_binary_and_numerical_features(test_hf_df_MNAR)

In [213]:
test_hf_MAR_mask_num, test_hf_MAR_mask_cat = generate_masks_for_missingness(
    ref_hf_df,
    test_hf_df_MAR,
    feat_m2, 
    feat_c2
)

No missingness!

In [227]:
test_hf_MNAR_mask_num, test_hf_MNAR_mask_cat = generate_masks_for_missingness(
    ref_hf_df,
    test_hf_df_MNAR,
    feat_m2, 
    feat_c2
)

No missingness!

##### Testing the correctness of these maps

In [244]:
test_hf_df_MAR[list(feat_m2)]

,serum_sodium,time,creatinine_phosphokinase,serum_creatinine,platelets,age,ejection_fraction
0,130.0,4.0,582.0,1.9,265000.00,75.0,20.0
1,NaN,NaN,7861.0,NaN,263358.03,NaN,NaN
2,129.0,7.0,146.0,1.3,162000.00,65.0,20.0
3,137.0,7.0,111.0,1.9,210000.00,50.0,20.0
4,116.0,8.0,160.0,2.7,327000.00,65.0,NaN
...,...,...,...,...,...,...,...
294,143.0,270.0,61.0,1.1,155000.00,62.0,38.0
295,NaN,NaN,NaN,1.2,270000.00,NaN,38.0
296,NaN,NaN,NaN,NaN,742000.00,NaN,60.0
297,140.0,280.0,2413.0,1.4,140000.00,45.0,NaN
298,136.0,NaN,196.0,NaN,395000.00,50.0,45.0

In [211]:
test_hf_MAR_mask_num

array([[0, 0, 0, ..., 0, 0, 0],
       [2, 2, 0, ..., 0, 2, 2],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [2, 2, 2, ..., 0, 2, 0],
       [0, 0, 0, ..., 0, 0, 2],
       [0, 2, 0, ..., 0, 0, 0]])

In [245]:
test_hf_df_MAR[list(feat_c2)]

,anaemia-is_no,anaemia-is_yes,diabetes-is_no,diabetes-is_yes,high_blood_pressure-is_no,high_blood_pressure-is_yes,sex-is_female,sex-is_male,smoking-is_no,smoking-is_yes
0,1.0,0.0,1.0,0.0,NaN,NaN,0.0,1.0,1.0,0.0
1,1.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,1.0,0.0
2,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0
3,0.0,1.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0
4,0.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...
294,1.0,0.0,NaN,NaN,NaN,NaN,0.0,1.0,0.0,1.0
295,NaN,NaN,NaN,NaN,1.0,0.0,NaN,NaN,NaN,NaN
296,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
297,1.0,0.0,1.0,0.0,NaN,NaN,0.0,1.0,0.0,1.0
298,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0

In [246]:
test_hf_df_MAR[list(feat_c2)]

,anaemia-is_no,anaemia-is_yes,diabetes-is_no,diabetes-is_yes,high_blood_pressure-is_no,high_blood_pressure-is_yes,sex-is_female,sex-is_male,smoking-is_no,smoking-is_yes
0,1.0,0.0,1.0,0.0,NaN,NaN,0.0,1.0,1.0,0.0
1,1.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,1.0,0.0
2,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0
3,0.0,1.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0
4,0.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...
294,1.0,0.0,NaN,NaN,NaN,NaN,0.0,1.0,0.0,1.0
295,NaN,NaN,NaN,NaN,1.0,0.0,NaN,NaN,NaN,NaN
296,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
297,1.0,0.0,1.0,0.0,NaN,NaN,0.0,1.0,0.0,1.0
298,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0

In [247]:
test_hf_df_MNAR[list(feat_m2)]

,serum_sodium,time,creatinine_phosphokinase,serum_creatinine,platelets,age,ejection_fraction
0,130.0,4.0,NaN,1.9,NaN,NaN,20.0
1,136.0,6.0,NaN,1.1,263358.03,55.0,38.0
2,129.0,7.0,146.0,NaN,162000.00,65.0,20.0
3,NaN,7.0,111.0,1.9,210000.00,50.0,20.0
4,116.0,8.0,160.0,2.7,327000.00,65.0,20.0
...,...,...,...,...,...,...,...
294,NaN,NaN,61.0,NaN,155000.00,62.0,38.0
295,139.0,NaN,1820.0,1.2,270000.00,55.0,38.0
296,NaN,NaN,2060.0,0.8,NaN,45.0,NaN
297,140.0,NaN,2413.0,1.4,140000.00,45.0,38.0
298,136.0,285.0,196.0,1.6,395000.00,50.0,45.0

In [250]:
test_hf_MNAR_mask_num

array([[0, 0, 2, ..., 2, 2, 0],
       [0, 0, 2, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [2, 2, 0, ..., 2, 0, 2],
       [0, 2, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [251]:
test_hf_df_MNAR[list(feat_c2)]

,anaemia-is_no,anaemia-is_yes,diabetes-is_no,diabetes-is_yes,high_blood_pressure-is_no,high_blood_pressure-is_yes,sex-is_female,sex-is_male,smoking-is_no,smoking-is_yes
0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,NaN,NaN
1,NaN,NaN,1.0,0.0,1.0,0.0,0.0,1.0,NaN,NaN
2,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0
3,NaN,NaN,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0
4,0.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
294,1.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0
295,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0
296,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0
297,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0
298,1.0,0.0,1.0,0.0,NaN,NaN,0.0,1.0,0.0,1.0

In [252]:
test_hf_MNAR_mask_cat

array([[0, 0, 0, ..., 0, 2, 2],
       [2, 2, 0, ..., 0, 2, 2],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [221]:
np.any(test_hf_MAR_mask_num==1)

False

In [234]:
np.any(test_hf_MAR_mask_cat==1)

False

In [222]:
np.any(test_hf_MNAR_mask_num==1)

False

In [225]:
np.any(test_hf_df_MNAR_cat==1)

False

The masking function applies perfectly to the as datasets without missingness well!